[build]
  command = "yarn build"
  publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self'; 
      script-src https://www.oliverturner.cloud https://www.oliverturner.dev https://www.codedsignal.co.uk https://*oliverturner.netlify.com google.com
    '''
    Feature-Policy = "usermedia self"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"