[build]
  command = "yarn build"
  publish = "_site"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self'; 
      script-src 'self' google.com;
      style-src 'self' 'unsafe-inline';
      object-src 'none'
    '''
    Feature-Policy = "usermedia self"
    Referrer-Policy = "same-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"